[workspace]
resolver = "3"
members = [
  "crates/rfs-api",
  "crates/rfs-cache",
  "crates/rfs-cliApp",
  "crates/rfs-models",
  # "crates/rfs-fuse",     # <-- commenta su Windows
  "crates/rfs-winfsp"      # <-- commenta su Linux/macOS
]
