[package]
name = "rfs-cliApp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.41", features = ["derive"]}
ctrlc = "3.4.7"
daemonize = "0.5.0"
fuser = "0.15.1"
rfs-api = { version = "0.1.0", path = "../rfs-api" }
rfs-cache = { version = "0.1.0", path = "../rfs-cache" }
rfs-fuse = { version = "0.1.0", path = "../rfs-fuse" }
rfs-fuse-macos = { version = "0.1.0", path = "../rfs-fuse-macos" }
rfs-models = { version = "0.1.0", path = "../rfs-models" }
signal-hook = "0.3.18"
