[package]
name = "rfs-fuse"
version = "0.1.0"
edition = "2024"

[dependencies]
fuser = "0.15.1"
futures-util = "0.3.31"
libc = "0.2.174"
rfs-models = { version = "0.1.0", path = "../rfs-models" }
tokio = "1.47.1"
