POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "5000",
  "password": "admin"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "5000",
  "password": "wrong password"
}

###

GET http://localhost:3000/api/me
Content-Type: application/json

{}

###

POST http://localhost:3000/api/logout
Content-Type: application/json

{}

###

// Get attributes of file with inode 1
GET http://localhost:3000/api/files/1/attributes

###
// Lookup file named "file2.txt" in directory with inode 190192
GET http://localhost:3000/api/directories/190192/entries/file2.txt/lookup

###

// List entries in root directory (inode 1)
GET http://localhost:3000/api/directories/1/entries


###
// Create a new directory named "prova" in directory with inode 1
POST http://localhost:3000/api/directories/1/dirs/prova

###
// Remove the directory named "prova" in directory with inode 1
DELETE  http://localhost:3000/api/directories/1/dirs/prova

###
// Create a new file named "pippo.txt" in directory with inode 1
POST http://localhost:3000/api/directories/1/files/pippo.txt

###
// Delete the file named "pippo.txt" in directory with inode 1
DELETE   http://localhost:3000/api/directories/1/files/pippo.txt

###
// Rename the file "pippo.txt" to "pippo_modificato.txt" in directory with inode 1
PATCH http://localhost:3000/api/directories/1/entries/pippo.txt
Content-Type: application/json

{
  "newParentIno": 1,
  "newName": "pippo_modificato.txt"
}

###
// Change the mode of the file with inode 190192 to 0o444
PATCH  http://localhost:3000/api/files/190192/attributes
Content-Type: application/json

{
  "perm": 493
}

###
POST http://localhost:3000/api/directories/1/files/pippo.txt

###
// Making an hard link
POST http://localhost:3000/api/links/1575933
Content-Type: application/json

{
  "linkParentIno": "1",
  "linkName": "pippo_link.txt"
}

###
// Delete the link
DELETE   http://localhost:3000/api/directories/1581812/files/pippo_link.txt

###
// Making a symbolic link
POST http://localhost:3000/api/symlinks
Content-Type: application/json

{
  "linkParentIno": "1",
  "linkName": "pippo_symlink.txt",
  "targetPath": "/pippo.txt"
}
