# GET

GET http://localhost:3000/api/directories
Content-Type: application/json

{
  "path": "../../../../../../"
}

###

POST http://localhost:3000/api/directories/prova-file-system-remoto
Content-Type: application/json

{
  "path": "../../../../../../"
}

###

DELETE  http://localhost:3000/api/directories/prova-file-system-remoto
Content-Type: application/json

{
  "path": "../../../../../../"
}

###
POST http://localhost:3000/api/files/prova.txt
Content-Type: application/json

{
  "path": "../../../../../../"
}

###
PUT http://localhost:3000/api/files/prova.txt
Content-Type: application/json

{
  "path": "../../../../../../",
  "text": "ciao mondo"
}

###
GET http://localhost:3000/api/files/prova.txt
Content-Type: application/json

{
  "path": "../../../../../../"
}

###
DELETE   http://localhost:3000/api/files/prova.txt
Content-Type: application/json

{
  "path": "../../../../../../"
}